### PR TITLE
Iterables

### PR DESCRIPTION
**Pull request by marcoarib**

### CODE REVIEW

**Comment by kiniggit** [comment]
Hey, Marco! Could you join all commits in only 1?

**Comment by kiniggit** [comment]
Btw, did you check if the english version had changes? Some pt-br articles are way back... https://github.com/javascript-tutorial/en.javascript.info

**Comment by marcoarib** [comment]
> Hey, Marco! Could you join all commits in only 1?

How can I do that? I'm not familiarized with Github editing. 
Thanks.

**Comment by kiniggit** [comment]
> > Hey, Marco! Could you join all commits in only 1?
> 
> How can I do that? I'm not familiarized with Github editing.
> Thanks.

No problem. Are you using the command line? Check out this link: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by kiniggit** [comment]
Also, I've seen in your translation that you're translating code aswell. We should keep the source code as in the original and only translate comments.

**Comment by kiniggit** [comment]
Later on, whenever you want to change your last commit, like picking up from where you left off you should use `git commit --amend` check it out more details in https://www.atlassian.com/br/git/tutorials/rewriting-history

**Comment by marcoarib** [comment]
> > > Hey, Marco! Could you join all commits in only 1?
> > 
> > 
> > How can I do that? I'm not familiarized with Github editing.
> > Thanks.
> 
> No problem. Are you using the command line? Check out this link: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

I'm using browser.

**Comment by kiniggit** [comment]
Hey, marco! Could you finish up reviewing https://github.com/javascript-tutorial/pt.javascript.info/pull/121 ? I've already done a thorough review and Ana already changed what had to be changed. We need 2 people to review n order to approve the PR. Cheers!

**Comment by kiniggit** [comment]
> > > > Hey, Marco! Could you join all commits in only 1?
> > > 
> > > 
> > > How can I do that? I'm not familiarized with Github editing.
> > > Thanks.
> > 
> > 
> > No problem. Are you using the command line? Check out this link: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git
> 
> I'm using browser.

I don't know how to squash commits using github site, but let me know when you're done and I'll try to squash your commits over here. Ok?

**Comment by odsantos** [comment]
Hi @marcoarib please could you also resolve the conflicts? Thank you.

**Comment by odsantos** [comment]
Hi @marcoarib , "**Object.keys, values, entries**" is not part of "**Iterables**".
Would you remove it from this Pull Request and create a separate one for it?
Would you also resolve the conflicts?
Thanks.

**Comment by nazarepiedady** [comment]
@Peruibeloko, @jonnathan-ls, @odsantos, we need some solution to this pull request. I am thinking on to close it and start a new one with updates applied and conflicts resolved.

**Comment by nazarepiedady** [comment]
@Peruibeloko, @jonnathan-ls, @odsantos, we need some solution to this pull request. I am thinking on to close it and start a new one with updates applied and conflicts resolved.

**Comment by Peruibeloko** [comment]
@nazarepiedady I'll fork and update it

**Pull request closed without merging**
