### PR TITLE
Polyfills and transpilers

### PR DESCRIPTION
**Pull request by odsantos**

### CODE REVIEW

**Review by jjuliomarttins — APPROVED** [review]

**Comment by odsantos** [comment]
Hi @jjuliomarttins please do not approve pull requests.
Only maintainers should review and approve them. 
Thank you.

**Comment by odsantos** [comment]
Wrong commit entries.

**Review by jonnathan-ls — APPROVED** [review]
LGTM (Looks good to me) ❤️ 

I added a commit (e362f460c93857b735da55bf7a094545eeeda525) with small simple changes

**Comment by odsantos** [comment]
> LGTM (Looks good to me) ❤️
> 
> I added a commit ([e362f46](https://github.com/javascript-tutorial/pt.javascript.info/commit/e362f460c93857b735da55bf7a094545eeeda525)) with small simple changes

Thanks.

**Comment by jonnathan-ls** [comment]
@nazarepiedady pode avaliar este PR?

Já tem a aprovação por um maintainer e também de outro colaborador

**Pull request merged**
