### PR TITLE
Developer console

### PR DESCRIPTION
**Pull request by jonnathan-ls**
# [Developer console](https://javascript.info/devtools)

## 📝 **Goal**

> Article update

## ☑ What was done?

- Remaining translation of pending text
- Updating images according to the pt language
- Fixed broken links

### CODE REVIEW

**Comment by jonnathan-ls** [comment]
> https://github.com/javascript-tutorial/pt.javascript.info/pull/241#issuecomment-1152815163

There is still text that has not been translated.

**Comment by odsantos** [comment]
> > Error: the article already translated in the Progress Issue #1 interrobang
> > [#241 (comment)](https://github.com/javascript-tutorial/pt.javascript.info/pull/241#issuecomment-1152815163) [javascript-translate-bot](https://github.com/javascript-translate-bot)
> 
> There is still text that has not been translated.

Hi,

Do you intend to translate what is missing?
It would be helpful to review complete lessons.

Thanks, Osvaldo.

**Comment by nazarepiedady** [comment]
@Peruibeloko, could you help to make this pull request to walk forward?

**Comment by nazarepiedady** [comment]
@jonnathan-ls, do you have some time to review this pull request?

**Review by Peruibeloko — APPROVED** [review]

**Comment by nazarepiedady** [comment]
@jonnathan-ls, could you fix the conflicts to approve the pull request?

**Review by nazarepiedady — APPROVED** [review]
It is good to be applied.

**Comment by jonnathan-ls** [comment]
Considering that this PR is about simple adjustments (grammatical correction and addition of pending translation), with the approval of two reviewers @Peruibeloko and @nazarepiedady, I am accepting this PR to apply the update.

**Review by jonnathan-ls — COMMENTED** [review]
Considering that this PR is about simple adjustments (grammatical correction and addition of pending translation), with the approval of two reviewers @Peruibeloko and @nazarepiedady, I am accepting this PR to apply the update.

**Pull request merged**
