### PR TITLE
Class checking: "instanceof"

### PR DESCRIPTION
**Pull request by danilolmc**

### CODE REVIEW

**Review by odsantos — CHANGES_REQUESTED** [review]
Hi @danilolmc ,

Here is a review.

"importance: 5"  is not translated (the number here is only an example).

Please, do not forget to replace English hyperlinks with Portuguese ones when those are available and their explanation is good enough for being a replacement.

I appreciate it if you tell me if you disagree with any suggestion.

Thank you,
Osvaldo.

**Review by odsantos — APPROVED** [review]
Hi @danilolmc ,

We'll need to wait for a review by another maintainer for merging this translation.

Thank you,
Best wishes.

**Review by jonnathan-ls — APPROVED** [review]
Looks Good To Mee

**Pull request merged**
