### PR TITLE
Update README and CONTRIBUTING

### PR DESCRIPTION
**Pull request by Peruibeloko**
Forkei a branch do @jonnathan-ls, atualizei ela com o estado da master, corrigi algumas seções e adicionei o guia de contribuição para traduções

### CODE REVIEW

**Comment by Peruibeloko** [comment]
@odsantos @nazarepiedady

**Comment by jonnathan-ls** [comment]
Boa @Peruibeloko 🚀, vou deixar minha revisão em cima do que adicionou.

Como já era uma tarefa em andamento #404, para não acabarmos com 2 PRs abertos (desnecessariamente), antes de abrir um novo através de fork, podemos tentar contribuir direto na branch do usuário que abriu o PR (caso não for protegida).

Eu estou procurando realizar dessa forma(*) quando busco revisar um PR ... contribuindo diretamente em vez de apenas apontar solicitações simples (ortografia, concordância, melhorias, etc)

> \(*) basicamente, aponto para o repo remoto do usuário que abriu a PR, mudo para a branch e faço o commit diretamente

De qualquer modo, não vejo problema ter esse segundo PR.
Irei encerrar o outro PR que tinha sido aberto e deixar apenas este em andamento ❤️

**Review by jonnathan-ls — APPROVED** [review]
LGTM ❤️

**Comment by jonnathan-ls** [comment]
Concordo @Peruibeloko acho válido também.

Não conheço essa parte de como ocorre a proteção se é a nível do usuário, repositório, ou branch ...
Vou dar uma vasculhada para entender melhor, se for a nível de repositório/branch ai vejo que faz sentido, já que fica limitado, mas se for a nível de usuário já não sei se seria uma recomendação boa.

**Comment by Peruibeloko** [comment]
Fica a nível de PR, você pode marcar sua PR como protegida ou não

**Comment by nazarepiedady** [comment]
To be honest and transparent, I do not like this mixture between English and Portuguese, or it is all Portuguese or not. I think this getting too far, are we translating the content to Portuguese or not?

Furthermore, I believe that we have the opportunity to present to all Portuguese-speaking people how to reference technical content using just Portuguese. I need to share that find English words which could be easily translated to Portuguese while reading content that supposed to be Portuguese makes me feel sick many times.

When we decide to study some content, we expect to learn new things because it was to stick to old things we would not study either. We can do better, for example, instead let **website** as it is, I could easily translate **website** as **local da Web** or **sítio da Web**. This mixture between English and Portuguese is horrible, and mines the comprehension.

Are the programmers so dumb that they could not understand or find ways to understand what they do not understand at first?

What is the reason behind the existence of dictionaries?

@Peruibeloko, @jonnathan-ls, @odsantos.

**Comment by Peruibeloko** [comment]
@nazarepiedady I'm going to ignore all the unnecessary criticism and reply exclusively to this: "Why mix Portuguese and English when there are perfectly valid alternatives for Portuguese?"

Simple, because no one uses the Portuguese counterpart. This repo is not supposed to be the last bastion of the Portuguese language, our safe haven from the evil English. Its a tutorial, its supposed to teach us JavaScript, not Portuguese.

People come here to better understand a programming language. Sure, we're already translating lots of stuff that could be kept in english, but if our focus starts shifting from "translating a tutorial" to "eliminating english from the tutorial" things would go downhill pretty quickly.

And personally, if some material I'm using to study a topic has me looking up definitions of words for my own language every paragraph, you bet I'll not be using that material.

**Comment by nazarepiedady** [comment]
We are translating a content from a language to another and have both languages mixed in the result that is supposed to be the translated one does not make sense, so we could just tell to everyone to learn the original language.

Not being used is not an excuse to keep doing the same, and what do you mean about nobody use them Portuguese counterparts? Did you read all Portuguese translated material available?

Also, who said that English is evil?

Are you saying that our colleagues are the same kind of idiots that expect to be familiar with every word they find in every material or subject they decided to study?

If we are studying something, it is obvious that we will encounter words and concepts that we are not familiar with, even if those words belong to our speaking language.

I can see this going to nowhere. First, we will use Portuguese, which is Brazilian, and then now we will mix up both languages, English and Portuguese. I know that, as always, people will just ignore this. Now, I can understand even more why the Chinese, French, Russian, and Spanish translations are so shiny and always better because they have identity.

So, let's continue doing what we were doing until this moment. Now I know the shape of the path we are following. I will remember this on the reviews and contributions I do.

@Peruibeloko

**Comment by nazarepiedady** [comment]
@Peruibeloko, since there are already two people agreeing with the changes, you can merge it already.

**Review by nazarepiedady — APPROVED** [review]
It seems good, and we all agreed with the changes.

**Pull request merged**
