### PR TITLE
Function expressions and arrows

### PR DESCRIPTION
**Pull request by odsantos**
Added translation to Function expressions and arrows directory files

### CODE REVIEW

**Comment by iliakan** [comment]
Why did you assign that to me?

**Comment by odsantos** [comment]
So that you were aware of it and people might contact you if I were unavailable. I'll remove.

**Comment by iliakan** [comment]
@odsantos I'm really sorry I'm not familiar with Portuguese. So I can't say anything here. I can merge. Should I? 

P.S. You can merge also.
P.P.S. Please ping me for technical stuff and for things that can be solved without knowing Portuguese =)

**Comment by odsantos** [comment]
@iliakan I am ver sorry I've put you in an uncomfortable situation. No, please don't merge. We need another maintainer for reviewing my PRs. Meanwhile, I expect to be able to leave them open. Thank you. It's nice to communicate with you.  Hopefully,  until soon.

**Comment by odsantos** [comment]
Files were split. Trying to have translations available as such. Thank you.

**Pull request closed without merging**
