### PR TITLE
Function expressions

### PR DESCRIPTION
**Pull request by AlexPHorta**

### CODE REVIEW

**Comment by kiniggit** [comment]
Hey, Alex! Could you update your translation with respect to the english version? https://github.com/javascript-tutorial/en.javascript.info/tree/master/1-js/02-first-steps/16-function-expressions

**Comment by AlexPHorta** [comment]
> Hey, Alex! Could you update your translation with respect to the english version? https://github.com/javascript-tutorial/en.javascript.info/tree/master/1-js/02-first-steps/16-function-expressions

Hi, I can, but first let me ask you one thing. Why doesn't the portuguese version follow the numbering of the english one? Look, the article you're asking me to translate is this one below, only its number is 15 instead of 16, and the name is slightly different.

https://github.com/javascript-tutorial/pt.javascript.info/blob/master/1-js/02-first-steps/15-function-expressions-arrows/article.md

**Comment by kiniggit** [comment]
Hey! I've noticed that aswell, the problem is that 1 article was added in the english version https://github.com/javascript-tutorial/en.javascript.info/tree/master/1-js/02-first-steps/12-nullish-coalescing-operator, which lead to a change of ordering in the following articles (I think iliakan and others also changed the ordering for other reasons).  If you see the english version, the Function expressions that you translated is now in the https://github.com/javascript-tutorial/en.javascript.info/tree/master/1-js/02-first-steps/17-arrow-functions-basics . Regarding the portuguese version, the Function expressions article.md is already translated. So I think the best approach here with respect to your PR would be to check for changes with the english version (solution and task) then merge. After that, we could check for changes in the main article and open a different PR to move the article to its correct position in 17-arrows-funcions-basics so it will match the english version. Let me know what you think.

**Comment by AlexPHorta** [comment]
To be honest, I would suggest simply drop my PR and firstly solve that discrepancy, it's only a couple of lines anyway.

Being brutally honest, I'm brazilian and I must tell you, reading stuff in european and brazilian portuguese mixed is awkward. Besides, it makes me uncertain if some sentence I'm reading is european portuguese or a sloppy brazilian translation.

Wouldn't iliakan consider a split in two versions? 

> Hey! I've noticed that aswell, the problem is that 1 article was added in the english version https://github.com/javascript-tutorial/en.javascript.info/tree/master/1-js/02-first-steps/12-nullish-coalescing-operator, which lead to a change of ordering in the following articles (I think iliakan and others also changed the ordering for other reasons).
> 
> In one comment iliakan oriented us to follow the english version as it is consistent with what is live in the website.
> 
> If you see the english version, the Function expressions that you translated is now in the https://github.com/javascript-tutorial/en.javascript.info/tree/master/1-js/02-first-steps/17-arrow-functions-basics not in the 16, which is the link I sent you (sorry!).
> 
> Regarding the portuguese version, the Function expressions article.md is already translated. So I think the best approach here with respect to your PR would be to check for changes with the english version (solution and task) then merge. After that, we could check for changes in the main article and open a different PR to update and move the article to its correct position in 17-arrows-funcions-basics so it will match the english version. Let me know what you think.

**Comment by odsantos** [comment]
Greetings,
The files on this PR no longer are in the folder.
It may be preventing an update to #65.
The former can be closed for a soon update.
Regards.

**Comment by odsantos** [comment]
Hi, if you don't mind I'll close this PR for proceeding to update the former #65.

**Pull request closed without merging**
