### PR TITLE
Translating polyfills and transpilers section.

### PR DESCRIPTION
**Pull request by kaellandrade**
Translating polyfills and transpilers section.

### CODE REVIEW

**Comment by odsantos** [comment]
Hi @kaellandrade this translation might already be in progress. Are you proposing changes?

**Comment by kaellandrade** [comment]
Yes @odsantos, in addition to including some more information about transpilers, I updated some links that are currently broken on the official page, for example: https://kangax.github.io/compat-table/es6/ to https://compat-table. github.io/compat-table/es6/

**Comment by odsantos** [comment]
@kaellandrade I'll check as soon as possible. Thanks.

**Comment by odsantos** [comment]
Hi @kaellandrade , on the top of [this](https://github.com/javascript-tutorial/pt.javascript.info/issues/1) page there are rules for translations. Since this topic is already taken, would you kindly make your suggestions under #215 ? Thanks.

**Comment by jonnathan-ls** [comment]
@kaellandrade como o Odair comentou, o artigo deste PR já estava em andamento, mas como ele também registrou, fique a vontade para sugerir alterações com base no PR que está aberto #215 

Para verificar as regras de contribuição e artigos ja traduzidos ou em andamento, consulte #1 (Portuguese Translation Progress)

@odsantos considerando que esta solicitação acabou ficando duplicada, tudo bem em fecharmos este PR?

**Comment by odsantos** [comment]
@jonnathan-ls yes, it should be closed. I would leave it to @kaellandrade first. Thanks.

**Comment by odsantos** [comment]
@kaellandrade if you wish we'd appreciate it if you'd make your suggestion on #215 . This PR is expected to be closed soon. Thanks.

**Comment by kaellandrade** [comment]
Fechando o PR devido a duplicidade #215

**Pull request closed without merging**
