### PR TITLE
Constructor, operator "new"

### PR DESCRIPTION
**Pull request by PedroDousseau**
Hello, just came back from a long time ago. I saw that my name is still linked with this article so i decided to continue with the translation of it.

I don't have access anymore to the other PR I opened (https://github.com/javascript-tutorial/pt.javascript.info/pull/88), so I'm creating this one, hope it's ok.

Let me know if there's something missing,

### CODE REVIEW

**Comment by odsantos** [comment]
Hi @PedroDousseau ,

The following files seem missing:
- 1-js/04-object-basics/06-constructor-new/2-calculator-constructor/_js.view/test.js
- 1-js/04-object-basics/06-constructor-new/3-accumulator/_js.view/solution.js
- 1-js/04-object-basics/06-constructor-new/3-accumulator/_js.view/test.js

Are you going to include them?

Thank you,
Osvaldo.

**Comment by PedroDousseau** [comment]
> Hi @PedroDousseau ,
> 
> The following files seem missing:
> 
>     * 1-js/04-object-basics/06-constructor-new/2-calculator-constructor/_js.view/test.js
> 
>     * 1-js/04-object-basics/06-constructor-new/3-accumulator/_js.view/solution.js
> 
>     * 1-js/04-object-basics/06-constructor-new/3-accumulator/_js.view/test.js
> 
> 
> Are you going to include them?
> 
> Thank you, Osvaldo.

Oh, I forgot them. I just translated

**Review by jonnathan-ls — APPROVED** [review]
LGTM ❤️ ( Looks Great To Me )

**Review by nazarepiedady — APPROVED** [review]
It is good to be merged to the master.

**Pull request merged**
