### PR TITLE
Eval: run a code string

### PR DESCRIPTION
**Pull request by odsantos**
This PR is a follow-up of  @AshuraDev work on #159, which account was deleted.

I added the solution to the other two translations.

### CODE REVIEW

**Review by renatocfrancisco — APPROVED** [review]
LGTM!

**Review by jonnathan-ls — APPROVED** [review]
LGTM

Embora o @renatocfrancisco precisa ser adicionado como revisor para contribuição do repositório, acho válido considerar a revisão dele para este PR ❤️, além disso, o @odsantos já tinha atuado como revisor no PR a qual deu origem a esta solicitação #159. Sendo assim, acho válido o aceite deste PR.

O que acham, demais `maintaners´? 

@luizclr, @Mr-Saxobeat, @leopoldovcfonseca

**Comment by odsantos** [comment]
@jonnathan-ls , probably @renatocfrancisco could submit translations first to see if it would be possible to ask @iliakan to include him as a maintainer.
Regards.

**Comment by renatocfrancisco** [comment]
@odsantos nah i don't think I'll translate anything. I'll just review some PR. Hopefully I'm useful :)

**Comment by odsantos** [comment]
@renatocfrancisco on the [Portuguese Translation Progress](https://github.com/javascript-tutorial/pt.javascript.info/issues/1) and under "Team translation" there is a link that tells that it is a maintainer task.

**Comment by jonnathan-ls** [comment]
@nazarepiedady consegue revisar? ❤️ PR tranquilo rs
Já tem duas revisões (01 maintainer e de outro colaborador)

**Pull request closed without merging**
