### PR TITLE
Styles and classes

### PR DESCRIPTION
**Pull request by danilolmc**

### CODE REVIEW

**Review by nazarepiedady — APPROVED** [review]
It is good to be approved. Well done @danilolmc, and thanks for your efforts.

**Comment by nazarepiedady** [comment]
@jonnathan-ls, @Peruibeloko, do you two have time to give your reviews to this pull request?

**Comment by danilolmc** [comment]
> It is good to be approved. Well done @danilolmc, and thanks for your efforts.

Thanks @nazarepiedady

**Review by jonnathan-ls — APPROVED** [review]
LGTM ❤️ 

I added some simple fixes, in commit d9ed66d2aef3f70a7dd4a702387c6226ca9a3553

**Pull request merged**
