### PR TITLE
Mixins

### PR DESCRIPTION
**Pull request by danilolmc**

### CODE REVIEW

**Comment by odsantos** [comment]
Hi @DaniloLima122 ,

Appreciated your efforts.
Under the title **For New Translators**, on the top of #1 , you may find instructions for claiming the article and naming the pull request.

Would you please follow them?
Thanks.

**Comment by DaniloLima122** [comment]
Hi @odsantos ! 

Thank you for the tips!

Now I think the PR name is correct, according the name of the article!

**Comment by odsantos** [comment]
Hi @DaniloLima122 , it also is necessary to claim it in your name, according to the same instructions, thus you need to add a comment on that page with this title too. After that, if the bot does not reserve on your name and add this PR, a maintainer may do it manually. Thanks.

**Comment by DaniloLima122** [comment]
> Hi @DaniloLima122 , it also is necessary to claim it in your name, according to the same instructions, thus you need to add a comment on that page with this title too. After that, if the bot does not reserve on your name and add this PR, a maintainer may do it manually. Thanks. 

Hi @odsantos , thank you! It's done!

**Comment by odsantos** [comment]
Hi @DaniloLima122 , in the future please do not forget to claim first, then to give the PR the same name as on that page.
The bot could reserve it in your name, and usually it can also assign the PR later, but no worries the PR is there as well, done manually.
Thanks for your efforts.

**Comment by DaniloLima122** [comment]
> Hi @DaniloLima122 , in the future please do not forget to claim first, then to give the PR the same name as on that page.
> The bot could reserve it in your name, and usually it can also assign the PR later, but no worries the PR is there as well, done manually.
> Thanks for your efforts.

Hi @odsantos ! Great, I won't, thanks for your support! 😁

**Review by odsantos — CHANGES_REQUESTED** [review]
Hi @danilolmc ,

Here is a review.

Please keep the translation line numbers matching the original (English) even if there is too little or too much space, and if you do not mind, also translate the text inside strings, but not variable names as you did.

Appreciate it if you tell me where you might disagree with this revision.

Thank you,
Osvaldo.

**Comment by odsantos** [comment]
Hi @danilolmc ,

[Here](https://github.com/javascript-tutorial/pt.javascript.info/pull/382#issuecomment-1469007348), the bot explains how to indicate that a translation is ready for another review.

Your PR is still marked with "changes requested" under _Labels_ on the top right of this page, which was done by the bot after my review.

Having that label, maintainers might believe that something is still to be done, and not have a look at a PR unless much time has passed.

Since you still might wish to make changes, when you have finished would you tell the bot you're done?

Please, only comment with "/done" here, without quotes or anything else.

Meanwhile, I am afraid I'll wait for that and the subsequent bot request for another review.

Thank you,
Osvaldo.

**Review by odsantos — APPROVED** [review]
Hi @danilolmc ,

We need that two maintainers review a translation for merging it.
So, we'll wait for a review by another maintainer.

Thank you,
Best wishes.

**Review by jonnathan-ls — APPROVED** [review]
Looks Good To Mee

**Comment by jonnathan-ls** [comment]
> Error: the article has another translator @DaniloLima122, not @danilolmc in the Progress Issue #1. Please update the progress issue or ask maintainers to do so.

Updated

**Comment by danilolmc** [comment]
> > Error: the article has another translator @DaniloLima122, not @danilolmc in the Progress Issue #1. Please update the progress issue or ask maintainers to do so.
> 
> Updated

I had changed my github username, but I had already finished the translation before it was merged.

**Pull request merged**
