### PR TITLE
Update article.md

### PR DESCRIPTION
**Pull request by vmlage**

### CODE REVIEW

**Comment by odsantos** [comment]
Hello @vmlage ,

It seems that you only translated two lines of the article, so there isn't much to review there.
Besides that article, this folder also has three subfolders with files to be translated.

Thank you.

**Comment by odsantos** [comment]
Hi @vmlage ,

It seems you're taking more than a year on this translation.
Would you tell me when you might finish it?

I am afraid that, if you not available, we'll have to unlink you from this lesson.

Thanks,
Osvaldo.

**Comment by nazarepiedady** [comment]
@Peruibeloko, @jonnathan-ls, @odsantos, do you consider it a good idea to close this pull request?

**Comment by Peruibeloko** [comment]
@nazarepiedady go ahead and close it, lets free the topic for another contributor

**Pull request closed without merging**
