### PR TITLE
The "new Function" syntax

### PR DESCRIPTION
**Pull request by tfbio**

### CODE REVIEW

**Comment by odsantos** [comment]
Hi @tfbio would you please resolve the conflicts, or inform if you may be unavailable to continue with this PR? Thank you.

**Comment by odsantos** [comment]
Hi @tfbio I update this PR article to be conforming to the English version and now there conflicts.
Hope you still are able to resolve them.
Thank you.

**Comment by nazarepiedady** [comment]
what do you recommend colleagues to be done in this pull request?

**Review by jonnathan-ls — APPROVED** [review]
I fixed the conflicts (https://github.com/javascript-tutorial/pt.javascript.info/pull/156/commits/0394ddf9ad607db6c504533a994f2901854b8d21), and added some modifications ([https://github.com/javascript-tutorial/pt.javascript.info/pull/156/commits/8c915f899cd960f944738249666a5314b72d375b](https://github.com/javascript-tutorial/pt.javascript.info/pull/156/commits/8c915f899cd960f944738249666a5314b72d375b)) @nazarepiedady 

With this, I register my LGTM

**Review by nazarepiedady — APPROVED** [review]
It seems good to me, so I'll add it to the main branch.

**Pull request merged**
