### PR TITLE
Unicode: flag "u" and class \p{...}

### PR DESCRIPTION
**Pull request by Peruibeloko**
Tomei algumas liberdades em favor da legibilidade do artigo, facilitando a compreensão para programadores que talvez não tenham tanto contexto com alguns dos termos e conceitos usados.

### CODE REVIEW

**Review by nazarepiedady — APPROVED** [review]
It looks good to me, so I approved.

**Review by nazarepiedady — APPROVED** [review]
It is not perfect, but it is good enough to be approved.

**Comment by Peruibeloko** [comment]
@nazarepiedady which changes would you suggest for improving the translation?

**Comment by nazarepiedady** [comment]
@Peruibeloko, I need to think for some time, but just for now, the current result is good enough.

**Comment by Peruibeloko** [comment]
@nazarepiedady take your time! I'd like to make sure the contribution is the best it can be :D

**Comment by nazarepiedady** [comment]
@Peruibeloko, I would like to tell you that we are not translating this content using a particular spoken language specification, such as *pt-br* or *pt-pt* or *pt-ao*, so I recommend to revert translation of *character* word and all words you specified as coming from *pt-br* variant, words already existed in Portuguese before the regional variants and these are the ones we should focus on because they are present in the dictionaries of all variants of the language.

**Comment by nazarepiedady** [comment]
@odsantos, could you analyse my premises?

Do I am deceived?

**Comment by Peruibeloko** [comment]
@nazarepiedady This sounds perfectly reasonable, although I do have an argument to keep the changes.

I'm Brazilian, and as such, I will prioritize the Brazilian Portuguese translations of words, as it is my mother tongue. Since the repo isn't specified to be any one kind of Portuguese, why not keep words of different dialects around? The discussion over at the "Multi Portuguese Translation" hasn't been resolved, after all.

I believe we shouldn't strive for the "one true Portuguese" interpretation, but rather have a mutually intelligible version, where we keep regional variations around, as long as they don't hinder the legibility for everyone.

As is the case of "caractere", which isn't that far off from "character" and also more naturally maps to the plural "caracteres" better than Portugal's "carácter".

Makes sense?

P.S. I think we should look at how Spanish solved this issue, as they also have many different dialects

**Comment by Peruibeloko** [comment]
@nazarepiedady This sounds perfectly reasonable, although I do have an argument to keep the changes.

I'm Brazilian, and as such, I will prioritize the Brazilian Portuguese translations of words, as it is my mother tongue. Since the repo isn't specified to be any one kind of Portuguese, why not keep words of different dialects around? The discussion over at the #249 "Multi Portuguese Translation" hasn't been resolved, after all.

I believe we shouldn't strive for the "one true Portuguese" interpretation, but rather have a mutually intelligible version, where we keep regional variations around, as long as they don't hinder the legibility for everyone.

As is the case of "caractere", which isn't that far off from "character" and also more naturally maps to the plural "caracteres" better than Portugal's "carácter".

Makes sense?

P.S. I think we should look at how Spanish solved this issue, as they also have many different dialects

**Comment by nazarepiedady** [comment]
@Peruibeloko, the Spanish variants did not change too much from its origin, but the same we cannot say about Portuguese.

I think the @odsantos can give a good point about the process.

**Comment by Peruibeloko** [comment]
@nazarepiedady please refer to @RaphGH's comment on issue #249 for justification, Portuguese doesn't change that much

**Comment by odsantos** [comment]
@Peruibeloko , @nazarepiedady, 

I would suggest leaving it to the translator's choice, as @Peruibeloko says the most important is the most readable possible to the largest audience possible. 

He also gives a good example, citing "carácter" which seems related to a personality and not to a programming letter. 

Probably, when reviewing the translation, the maintainer could seek that common word to the largest audience and suggest a possible change, which I believe @nazarepiedady also already did by suggesting translating "matching" to "correspondência" (I'm not sure if this was the word) instead of "casar". 

Since the largest audience might be expecting Portuguese from Brazil, probably, we might only need to ask for a word change on this version, if a person not used to it might not understand the meaning of a word, which could lead to an undesirable effect on readers from other Portuguese variants to stay away from the site. 

From what I usually see, there is not much difference in written Portuguese between different variants of text for education, so perhaps we should have in mind the purpose of the text being translated and look for words we could use in this context rather than words we might use on informal oral communication, so then we possibly could see a translation for any audience.

Even here, I already saw translations from contributors from Brazil that look like that, as well as I am looking for time to change many of my old ones.

Thanks.

**Comment by Peruibeloko** [comment]
@odsantos thank you very much for your input!

The main reason I'm using the term "casar" instead of "corresponder" for translating "match" is due to a book I recently read on Regular Expressions, which used the term "casar".

Its also shorter :P

**Comment by nazarepiedady** [comment]
@odsantos, the commonly used Brazilian Portuguese, I mean the informal way or better, the day to day Brazilian Portuguese mislead the real meaning and comprehension of the things, what could be said about words that supposed to be translated, and there is some habit that I and many people that care clarity particularly hate, that is present on majority of translation effort (that is not particular to the Brazilian) which is the insistence in using loanwords where we already have words that clearly describe the meaning of the words in English.

And I do not see why it is so bad to learn more about Portuguese when you studying,  obviously there is more Portuguese than we used to in our day to day.

Many none Brazilian went out of the comfort zone to learn others variations of the Portuguese, because there is more Portuguese than we thing, mainly Brazilian, why the Brazilian could not do the same?

It is bad to use the Brazilian Portuguese as the rule, but I can see that this is a waste of time, so I will just let this here as a manifest of my preoccupations.

**Comment by Peruibeloko** [comment]
@nazarepiedady Could you please give some concrete examples on where my translation used loanwords that could be exchanged for native Portuguese?

I feel like your criticism is a bit unjustified if you don't provide any concrete examples on how things can improve, as other maintainers don't seem to have the same issue. Also, I don't think my translation is particularly informal in any meaningful way, to a point that degrades intelligibility at least.

My hopes here are to provide, as I've stated previously, the best translation I can. If I used some sort of loanword during the process, it's perhaps due to its bigger adoption that the native counterpart.

Which, by the way, I'm fully supportive of using native words when available! But that also must include some sort of explanation, or at least something that nods to the already well known loanword.

**Review by jonnathan-ls — APPROVED** [review]
Considering the discussion of the subject pertinent to the translation variant.

I don't think we should give emphasis the variant of the word, but rather make it understandable and easy for the reader to interpret.

To be honest, I worry more about having the repository with the translation carried out (following appropriate revisions, of course) than to assess the   details of one word or another.

I'm going to leave my LGTM, considering that reading the article is clear to me.

However, I confess that some excerpts left me reflecting when I read them, I'll sharing them here, see if it makes sense to you @Peruibeloko 

- `no Unicode`: the use of terme `no` sounded strange, it seems that the character is being inserted in `Unicode`, but in fact I understand that it is a repression of the character only.
  - In my opinion, using the one closest to the original excerpt makes the most sense: from `in Unicode` to `em Unicode`.
  - The term `in` is a contraction of a preposition with an article `in + o`, in this sense, `no Unicode` would be something like `in the Unicode` which does not correspond to the original content in English.

- `match`: using the term `casar` may be understandable for those who are already familiar with regex, but for those who are beginners and are beging  in the technology context, it may seem confusing and lead to faulty interpretation.
   - Using the term `correspondência` makes more sense, in addition, it is the term used when we research and study the [String.prototype.match](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/String/match), which is what MDN uses for explanation.

**Comment by Peruibeloko** [comment]
@jonnathan-ls thanks for the input!

Considering the given examples, I'll update the translation using the suggestions. I'll also take a minute to update all the other currently open items to reflect the change and have a concise naming scheme across the chapter.

**Comment by Peruibeloko** [comment]
@jonnathan-ls @nazarepiedady @odsantos I made the changes, updating the other articles as well

**Comment by nazarepiedady** [comment]
@Peruibeloko, @odsantos, you only know the Brazilian Portuguese. It is a waste of time trying to explain anything to you, which is different from us non-Brazillian who are familiar with Brazilian and non-Brazillian

To me, it is fine since you all already decided to follow the path of majority and not the path of correctly speaking Portuguese.

Let's go do it. 🤷‍♂️

**Comment by Peruibeloko** [comment]
@nazarepiedady I could make the argument that neither I, or you, or any individual person has a saying on what "correctly speaking Portuguese" is, but I get the feeling that you're not arguing in good faith, as during the entire conversation you didn't provide any actionable, concrete changes.

Your contribution was essentially unsubstantiated criticism of Brazilian Portuguese and their speakers, followed by an unhelpful "it is what it is" attitude, which is the complete opposite of what I proposed in all of my comments.

I hope that we can come to good terms during our time contributing to the project!

**Comment by nazarepiedady** [comment]
@Peruibeloko, you only know Brazilian Portuguese, I can not understand what I could say, I will only say that there is more Portuguese than that you are used to.

I have already encountered many Brazilians who understand what I am saying and know that the Portuguese of Brazil is not the problem, because there are words present in others variants, but the people choose the wrong words so they can not understand others Portuguese speaking people, it is sad, because Americans, British, Spanish and Mexican do not have the same problems.

**Comment by Peruibeloko** [comment]
@nazarepiedady Why do you assume I only know Brazilian Portuguese? I said its the one I know best, not the only one I know.

Why so you assume I'm not aware of the different dialects of Portuguese that there are? I'm well aware of them. Angola, Moçambique, Portugal, Cabo Verde, why would they all speak the same Portuguese?

And again, you use the word "wrong". What does it mean for a word to be wrong? Is there some sort of superior translation I'm unaware of? If the problem is that certain Brazilian words are unintelligible to non-Brazilians, the same can be said for words of different dialects that are unintelligible to Brazilians, as you said: "you can not understand what I could say". Is Brazilian Portuguese somehow lesser than others?

You again provided nothing but (wrong) assumptions about me and my knowledge of Portuguese, failed to consider that there **is no objective version of Portuguese**, and no concrete examples of the point you're trying to make.

I understand its your concern to make sure that non-Brazilians also must have access to this material (which is my concern as well), but without any sort of concrete examples that go against this, it just sounds like a criticism of Brazilian Portuguese in general.

**Comment by nazarepiedady** [comment]
@Peruibeloko, to me, it is not a problem at all using the Brazilian Portuguese to translate the material, I am already aware that Brazilians think the only Portuguese possible is Brazilian.

Let's stop with this and start to work on the translation of the content.

**Comment by Peruibeloko** [comment]
@nazarepiedady fair enough.

@odsantos @jonnathan-ls @iliakan I think its important we're all aware of this perception. Let's get back to work!

**Pull request merged**
