### PR TITLE
Private and protected properties and methods

### PR DESCRIPTION
**Pull request by danilolmc**

### CODE REVIEW

**Comment by nazarepiedady** [comment]
@jonnathan-ls, @odsantos,  what do you think?

**Comment by jonnathan-ls** [comment]
> ... what do you think?

Sobre o que? rs 😄 não entendi ><
Refere-se a revisão deste PR?

**Review by jonnathan-ls — APPROVED** [review]
LGTM ❤️ 

Tinha algumas necessidades simples e tradução pendente, então acabei contribuindo com um novo commit https://github.com/javascript-tutorial/pt.javascript.info/pull/410/commits/0eba7f5bfcbd90897d8ee8dd63c6f4de4474ab2a.

**Review by nazarepiedady — APPROVED** [review]
I approve the review since the last commit did what the pull request was needing about some language and grammatical corrections.

**Pull request merged**
